# Generated by Django 5.2.4 on 2025-08-20 13:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Expense amount in dollars', max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('shopping', 'Shopping'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('other', 'Other')], help_text='Select the category that best describes this expense', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when the expense was incurred'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, help_text='Optional detailed description of the expense'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(help_text='Brief description of the expense', max_length=100),
        ),
    ]
